### ISSUE TITLE
Functions ignored during deploy when base directory is not repo root

### ISSUE THREAD

**Issue by joserocha3** [nhost/nhost#848] opened 2022-07-22 13:17 UTC
I have a function that I am using as a Hasura action. Everything works as expected locally, using the CLI, however when the project deploys in the cloud the functions do not get built.

I am I doing something wrong? Or is there somewhere I can see detailed deployment logs?

Version: Nhost CLI v0.6.12 for darwin-amd64

**Functions located in `functions` directory:**
![180446920-58ddde16-7d00-431f-acb0-4c77068ee470](https://user-images.githubusercontent.com/11415340/180453452-06342e93-dff2-4aff-a567-463bf4bd85a2.png)

**Deploy occurs after committing to repo, but no functions were built:**
![Screen Shot 2022-07-22 at 8 05 51 AM](https://user-images.githubusercontent.com/11415340/180446345-17b3a098-358c-4448-aabe-cde62452f80d.png)

**No functions listed:**
![Screen Shot 2022-07-22 at 8 06 17 AM](https://user-images.githubusercontent.com/11415340/180445524-7001a09d-711c-408f-a6ed-d31eb4ab7818.png)

**Server returns generic error, if I change the function name to gibberish I get the same error message returned:**
![Screen Shot 2022-07-22 at 8 09 22 AM](https://user-images.githubusercontent.com/11415340/180445904-2f675f13-5986-4c15-8480-7a3d9b44347e.png)

**It works when running locally:**
![Screen Shot 2022-07-22 at 8 09 08 AM](https://user-images.githubusercontent.com/11415340/180445907-db6ddbb3-4dd6-4d1d-a368-e8d7b024d43a.png)

**Comment by reisupdev** [comment] 2022-07-22 14:06
I'm not on your machine but I suspect your problem is that you're including code from a shared folder _locally_ that isn't in the repo you're syncing to NHost.

**Comment by reisupdev** [comment] 2022-07-22 14:06
<img width="556" alt="Screen Shot 2022-07-22 at 10 03 52 AM" src="https://user-images.githubusercontent.com/107378803/180456461-6687e4be-9c34-43f2-a13c-422db2cd7939.png">

**Comment by pkreipke** [comment] 2022-07-22 14:08
I'm not on your machine but I suspect your problem is that you're including code from a shared folder locally that isn't in the repo you're syncing to NHost.

**Comment by pkreipke** [comment] 2022-07-22 14:08
<img width="556" alt="Screen Shot 2022-07-22 at 10 03 52 AM" src="https://user-images.githubusercontent.com/12683108/180456854-aa929ed0-f4aa-4d01-8e1b-546737765f45.png">

**Comment by joserocha3** [comment] 2022-07-22 15:18
@pkreipke thank you for chiming in! That shared folder is part of the repo.

It not directly in the `api` directory though, which is where nhost is, maybe that is the issue?

**VS Code:**
![Screen Shot 2022-07-22 at 10 15 31 AM](https://user-images.githubusercontent.com/11415340/180470332-96c443d3-0303-4f14-8c85-e7f94afc9dc5.png)

**GitHub:**
![Screen Shot 2022-07-22 at 10 16 29 AM](https://user-images.githubusercontent.com/11415340/180470460-10d0948e-0db1-4ab7-ae20-9fa18c62f5d5.png)

**Comment by joserocha3** [comment] 2022-07-22 15:27
I copied the `generated` directory and import from there instead, but that still did not work.

![Screen Shot 2022-07-22 at 10 26 20 AM](https://user-images.githubusercontent.com/11415340/180472386-a13996f8-4834-4618-9df7-acef1fae80cf.png)

**Comment by pkreipke** [comment] 2022-07-22 17:03
Out of an abundance of caution I named _all_ my utility folders, subfolders _and_ files with a leading prefix. I haven't tracked down the code to see if that's necessary (e.g. do files _inside_ a `_...` folder need a prefix too?).

E.g. in your screen above I would have named `useQuery.ts` as `_useQuery.ts`. I'm hoping this is not necessary for exactly the reason you're find above (copying a large quantity of files over). 

Have you tried a simple function with just a few sample imports with a mix of `_` as you have above to see if it gets deployed?

Otherwise you may need to get on Discord and ask for some quick help from an NHost person to track down deployment logs.

**Comment by pkreipke** [comment] 2022-07-22 19:02
This isn't promising:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/12683108/180506245-d9e0dba7-305e-487d-aa49-deaa05c05fb4.png">

**Comment by joserocha3** [comment] 2022-07-23 14:58
@pkreipke I figured out what the issue is. The issue is that nhost is not building functions found in a subdirectory. Migrations and metadata are picked up, but functions are not.

**Does NOT work:**
![Screen Shot 2022-07-23 at 9 55 35 AM](https://user-images.githubusercontent.com/11415340/180610418-b7210dbb-01d4-46ac-bee8-9eda85a62fbf.png)

**Does work:**
![Screen Shot 2022-07-23 at 9 55 55 AM](https://user-images.githubusercontent.com/11415340/180610416-164a16c8-63c9-44f9-9951-f21180846843.png)

**Base directory is set:**
![Screen Shot 2022-07-23 at 9 56 58 AM](https://user-images.githubusercontent.com/11415340/180610474-eb5299f0-53db-493e-ac07-dd6279001696.png)

**Comment by elitan** [comment] 2022-08-01 06:19
There are two bugs in this issue, and I've been able to reproduce both.

## 1. Functions are not built when using a subdirectory

> The issue is that nhost is not building functions found in a subdirectory. Migrations and metadata are picked up, but functions are not.

## 2. CLI doesn't skip endpoints for `_` file/folders.

**Comment by elephant3** [comment] 2022-08-03 11:16
@joserocha3 the fix has been rolled. Please re-trigger your deployment and let me know if it worked.

**Comment by elephant3** [comment] 2022-08-03 13:50
@joserocha3 thanks for reporting and sorry for this happening. The problem is that our system installs dependencies from the root dir, not from the base dir where `nhost` and `functions` are located. The fix is coming very soon...

**Comment by joserocha3** [comment] 2022-08-03 14:01
@elephant3 thank you for the explanation. I have copied the dependencies to a `package.json` in the repo root and the deploy works. Although, it is not ideal.

**Comment by elephant3** [comment] 2022-08-04 11:40
@joserocha3 please check now, it should pick up `package.json` from the base dir

**Comment by joserocha3** [comment] 2022-08-04 12:46
@elephant3 it failed with the below message:

![Screen Shot 2022-08-04 at 7 45 44 AM](https://user-images.githubusercontent.com/11415340/182850384-ee74db74-acb1-4376-9420-2c5ad83f35a8.png)

Shouldn't fail due to no license. Or maybe there is another error not shown in the logs?

**Comment by joserocha3** [comment] 2022-08-04 12:49
Oh, I think it might be because I have `package.json` in the repo root, and in the base directory. Could it be seeing the repo root `package.json` and attempting to process it?

![Screen Shot 2022-08-04 at 7 48 17 AM](https://user-images.githubusercontent.com/11415340/182850944-1c84ffa0-9d8f-451d-bcb5-dc4a3003ab87.png)

**Comment by elitan** [comment] 2022-08-04 13:07
@joserocha3 I assume your base directory (configured in the Nhsot Dashboard) is: `./api`?

**Comment by elephant3** [comment] 2022-08-04 13:23
@joserocha3 I can confirm from server logs that the `api/package.json` was used

**Comment by elephant3** [comment] 2022-08-04 13:29
@joserocha3 I found the issue, the fix is coming...

**Comment by joserocha3** [comment] 2022-08-04 13:46
> I your base directory (configured in the Nhsot Dashboard): ./api?

@elitan yes, it is

> I found the issue, the fix is coming...

Awesome 👍🏼 thank you @elephant3, if you still need the file contents let me know

**Comment by elephant3** [comment] 2022-08-04 14:51
@joserocha3 please re-trigger now and let me know if everything is fine

**Comment by elephant3** [comment] 2022-08-04 15:37
@joserocha3 awesome!

**Closed by elephant3** 2022-08-04 15:37 UTC
Labels: bug, functions
