### ISSUE TITLE
Can't access Hasura console 

### ISSUE THREAD

**Issue by vipafattal** [nhost/nhost#1064] opened 2022-10-20 17:57 UTC
I created a new project (Nhost Cloud not CLI), but I can't access the Hasura console.

When I paste the admin key that I copy from the Nhost project page it tells me "ERROR, try again?"

**Comment by elitan** [comment] 2022-10-24 06:42
I'm unable to reproduce this. 

- Can you maybe add some screenshots?
- Does it work if you create a new project?

**Comment by vipafattal** [comment] 2022-10-24 08:20
Here are the screenshots:

1. I open the Hasura tab in the cloud, and press on the admin secret copy icon
![image](https://user-images.githubusercontent.com/22567094/197480240-b0abc46f-199c-4893-bfc6-2438f5ed1085.png)

2. I paste my admin secret and hit on enter button
![image](https://user-images.githubusercontent.com/22567094/197480607-61880414-c38d-4b69-931a-29de35255690.png)

For newer projects no issues I tested it.

**Comment by guicurcio** [comment] 2022-10-24 10:32
Hey [vipafattal](https://github.com/vipafattal), do you see any of the other sections in the dashboard? Wondering if there's a problem with your Hasura instance or just your admin secret... if you see the other sections (e.g. users) throw me an email at guido@nhost.io with your subdomain so I can check what's going on with your instance 🤔

**Comment by nunopato** [comment] 2022-11-06 23:46
This seems to have been sorted out, so I will close it now. Feel free to re-open it if that is not the case.

**Closed by nunopato** 2022-11-06 23:46 UTC
Labels: dashboard
