### ISSUE TITLE
How to use image transformation with presigned urls?

### ISSUE THREAD

**Issue by viktorfa** [nhost/nhost#1430] opened 2022-12-25 13:24 UTC
The docs on https://docs.nhost.io/storage#image-transformation says `Image Transformation works on both public and pre-signed URLs.`

I can successfully transform image sizes with public urls, but not with presigned urls.

I tried to add `&w=200` as a search parameter to a presigned url, and was not surprised that AWS gave an error saying the url does not match the signature.
I also tried generating a url with `?w=200` when requesting a presigned url, i.e. `GET https://[subdomain].storage.eu-central-1.nhost.run/v1/files/[file-id]/presignedurl?w=200`. However, that did not work either, as the presigned url returned was just to the original image.

Are the docs wrong, or am I using the API wrong?

**Comment by elitan** [comment] 2022-12-25 13:33
Do you add the query parameters to the URL you're using to generate the pre-signed URL? This is correct.

Or do you add the query parameters to the already generated pre-signed URL? This won't work.

**Comment by viktorfa** [comment] 2022-12-25 14:10
Hi, thanks for the quick answer!

I'm adding the query params to the URL I'm using to generate the presigned URL. I'll attach a screen recording so you can see if I'm doing it correctly.

The image will be the original size even if I add `?w=200` to the URL used to generate the presigned URL.

[Peek 25-12-2022 15-07.webm](https://user-images.githubusercontent.com/5357936/209471081-03d51cd3-7ff2-4889-a354-5deb163a5071.webm)

**Comment by elitan** [comment] 2023-01-02 07:48
Ok, I just confirmed, and it's not yet doable. You can only transform public images for now.

We're tracking the issue here: https://github.com/nhost/hasura-storage/issues/104 (so I'm closing this issue for now)

**Comment by dohomi** [comment] 2023-03-17 11:40
exciting to see this feature land - the docs seem not to be updated but is https://docs.nhost.io/reference/javascript/storage/get-presigned-url now accepting the same props as https://docs.nhost.io/reference/javascript/storage/get-public-url ?

**Comment by dbarrosop** [comment] 2023-03-17 11:59
You are right, sorry about that. Let me reopen the issue until the SDK is fixed. For now the backend is ready (just need upgrading your version of the cloud which I can do on demand), which means you can get your presigned url as you usually do and then append your image manipulation options. For instance `presignedURL + "?w=1024&h=768"`.

**Closed** 2023-03-17 14:58 UTC
Labels: needs info

**Comment by dohomi** [comment] 2023-03-18 05:38
I am spinning my head around how to use `next/image` with getPresignedUrl - mainly because the loader of `next/image` can't be async. Do you guys have a demo on how that would look like?

**Comment by szilarddoro** [comment] 2023-03-20 11:32
I don't think that is possible because you'll also need to provide credentials in the URL. I don't think those are being passed to the custom loaders.

You can try using [Remote Patterns](https://nextjs.org/docs/api-reference/next/image#remote-patterns) and configure the transformation parameters through the image URL, not through the image component's props.

**Comment by dohomi** [comment] 2023-03-21 01:40
It would be great if an example of the remote patterns would be shown in [nextjs](https://github.com/nhost/nhost/tree/main/examples/nextjs) as it might be crucial for many Nhost users

**Comment by szilarddoro** [comment] 2023-03-21 09:08
Yeah, the examples should definitely be extended.

For now, what you could try is to add change your `next.config.js` based on this example (using the config from `examples/nextjs` as an example):

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**.nhost.run',
      },
    ],
  },
}

const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true'
})

module.exports = withBundleAnalyzer(nextConfig)
```

You can use a component like this to render pre-signed images:
```tsx
import { useNhostClient } from '@nhost/nextjs'
import Image from 'next/image'

export interface PresignedImageProps {
  /**
   * File identifier
   */
  id: string
  /**
   * Image width
   */
  width: number
  /**
   * Image height
   */
  height: number
  /**
   * Quality
   */
  quality: number
  /**
   * Blur
   */
  blur: number
}

export function PresignedImage({ id, ...params }: PresignedImageProps) {
  const client = useNhostClient()
  const presignedUrl = client.storage.getPresignedUrl({ fileId: id, ...params })

  return (
    <Image
      src={presignedUrl}
      width={params.width}
      height={params.height}
      alt={/* ... */}
    />
  )
}
```

**Comment by dohomi** [comment] 2023-03-22 01:55
>   const client = useNhostClient()
>   const presignedUrl = client.storage.getPresignedUrl({ fileId: id, ...params })
Isn't getPresignedUrl async? I know how to wrap that into a `useEffect` but still its not possible to use a dedicated `loader` to scale the images based on presigned URLs
<img width="1043" alt="Screenshot 2023-03-22 at 09 52 57" src="https://user-images.githubusercontent.com/489221/226781833-537693a5-45ec-47dc-bb21-f606767ade63.png">

**Comment by dohomi** [comment] 2023-03-22 02:42
> You are right, sorry about that. Let me reopen the issue until the SDK is fixed. For now the backend is ready (just need upgrading your version of the cloud which I can do on demand), which means you can get your presigned url as you usually do and then append your image manipulation options. For instance `presignedURL + "?w=1024&h=768"`.

How do I know which version I am running on inside of Nhost backend?

**Comment by szilarddoro** [comment] 2023-03-22 08:13
Yeah, it is, indeed. You'll need to fetch and store the value in the local state.

I'm not sure I follow why you want to use a dedicated `loader`. As I mentioned, it's not currently possible to use one to set up the parameters through the `<Image />` component's properties. You need to pass your scaling parameters (`width`, `height`) or other transformation parameters (`quality`, `blur`) directly to the `getPresignedUrl` function instead.

This is how I would change the component:

```tsx
export function PresignedImage({ id, ...params }: PresignedImageProps) {
  const [presignedUrl, setPresignedUrl] = useState<string>("");
  const client = useNhostClient();

  useEffect(() => {
    async function fetchPresignedUrl() {
      const fetchedUrl = await client.storage.getPresignedUrl({
        fileId: id,
        // Note: This object will contain your `width` / `height` / `quality` and `blur` values
        ...params,
      });

      // Here you need to extract the actual URL from the response object
      setPresignedUrl(fetchedUrl.presignedUrl?.url || "");
    }

    fetchPresignedUrl();
  }, [client.storage, id, params]);

  return (
    <Image
      src={presignedUrl}
      width={params.width}
      height={params.height}
      alt={/* TODO: Add alt text */}
    />
  );
}
```

You can of course enhance the behaviour by adding a loading state, and a fallback image in case the `presignedUrl` is empty. Let me know if you have any questions.

---

As for the other question:

> How do I know which version I am running on inside of Nhost backend?

You can send your subdomain to any of us on Discord, and we can check it for you.

**Comment by dohomi** [comment] 2023-03-22 08:24
I think that would be a perfect fit to extend the `@nhost/react` with a `usePresignedUrl` hook which handles the states. I am currently using it with react-query as follow:
```ts
export function usePresignedUrl({fileId, ...props}: UsePresignedUrlProps) {
    const {storage: {getPresignedUrl}} = useNhostClient()
    const {data, ...rest} = useQuery({
        queryKey: ['presignedUrl', props],
        enabled: !!fileId,
        queryFn: async () => {
            return getPresignedUrl({
                fileId,
                ...props
            })
        }
    })
    const url = data?.presignedUrl?.url ?? null
    return {url, ...rest}
}
```
it would be great addition if this could get included, especially for internal caching and other improvements.
