### ISSUE TITLE
redirect URLs remove hash parameters

### ISSUE THREAD

**Issue by mainstreetmark** [nhost/nhost#1272] opened 2022-12-01 14:32 UTC
When supplying a redirectTo to `useResetPassword`, the resulting URL in the email cuts off the hash parameters.

Since I'm using a SPA (particularly, Quasar), the whole operation runs on hash parameters.  As such, I cannot redirect to, for example, `http://localhost:8081/#/auth/reset`

I suspect the issue is that hash parameters are incompatible with ? parameters, but perhaps some cleverness could be applied by sticking the ? params before the # params...

**Comment by TEMHITHORPHE** [comment] 2022-12-13 10:25
So what does a solution look like?

**Comment by plmercereau** [comment] 2022-12-26 12:05
Duplicate of https://github.com/nhost/nhost/issues/832

**Closed by plmercereau** 2022-12-26 12:05 UTC
Labels: bug
