### ISSUE TITLE
Issues with @nhost/vue lib

### ISSUE THREAD

**Issue by shiftlabs1** [nhost/nhost#698] opened 2022-06-09 10:51 UTC
I get the below error when using the vue client lib both with nhost and hasura-auth , on method SignupEmailPassword

```
@nhost_vue.js?v=2ed4f1b0:2096 Missing onError handler and/or unhandled exception/promise rejection for invocation 'signUp'. Original error: 'TypeError: Cannot read properties of undefined (reading 'error')'.  Stacktrace was 'TypeError: Cannot read properties of undefined (reading 'error')
    at https://github-c6w3iu--3333.local.webcontainer.io/node_modules/.vite/deps/@nhost_vue.js?v=2ed4f1b0:5506:67
    at async postRequest (https://github-c6w3iu--3333.local.webcontainer.io/node_modules/.vite/deps/@nhost_vue.js?v=2ed4f1b0:6116:20)' Current error is 'Error: Unable to evaluate guard 'unverified' in transition for event 'error.platform.signUp' in state node 'nhost.authentication.registering':
Cannot read properties of undefined (reading 'status')'. Stacktrace was 'Error: Unable to evaluate guard 'unverified' in transition for event 'error.platform.signUp' in state node 'nhost.authentication.registering':
Cannot read properties of undefined (reading 'status')
    at StateNode2.next (https://github-c6w3iu--3333.local.webcontainer.io/node_modules/.vite/deps/@nhost_vue.js?v=2ed4f1b0:4562:17)
    at StateNode2.transitionLeafNode (https://github-c6w3iu--3333.local.webcontainer.io/node_modules/.vite/deps/@nhost_vue.js?v=2ed4f1b0:4458:26)
    at StateNode2._transition (https://github-c6w3iu--3333.local.webcontainer.io/node_modules/.vite/deps/@nhost_vue.js?v=2ed4f1b0:4535:19)
    at StateNode2.transitionParallelNode (https://github-c6w3iu--3333.local.webcontainer.io/node_modules/.vite/deps/@nhost_vue.js?v=2ed4f1b0:4484:33)
    at StateNode2._transition (https://github-c6w3iu--3333.local.webcontainer.io/node_modules/.vite/deps/@nhost_vue.js?v=2ed4f1b0:4540:17)
    at StateNode2.transition (https://github-c6w3iu--3333.local.webcontainer.io/node_modules/.vite/deps/@nhost_vue.js?v=2ed4f1b0:4746:32)
    at https://github-c6w3iu--3333.local.webcontainer.io/node_modules/.vite/deps/@nhost_vue.js?v=2ed4f1b0:3587:28
    at provide (https://github-c6w3iu--3333.local.webcontainer.io/node_modules/.vite/deps/@nhost_vue.js?v=2ed4f1b0:2414:16)
    at Interpreter2.nextState (https://github-c6w3iu--3333.local.webcontainer.io/node_modules/.vite/deps/@nhost_vue.js?v=2ed4f1b0:3586:21)
    at https://github-c6w3iu--3333.local.webcontainer.io/node_modules/.vite/deps/@nhost_vue.js?v=2ed4f1b0:3119:31'
```
The call is mainly as shown below 

```
	const { isSuccess, error,isError} = await signUpEmailPassword(
			formValues.email,
			formValues.password,
			{
				displayName: `${formValues.firstName} ${formValues.lastName}`,
				defaultRole: 'user',
				locale: 'en'

			})
```
The error is being thrown from the xstate package. Has anyone experienced this and knows how the issue can be resolved? 
I get this error but the user gets created

**Comment by plmercereau** [comment] 2022-06-10 14:44
Hello @shiftlabs1, I can't reproduce, could you share the contents of your `package.json`, or as you seen to use stackblitz, a link to the project with the error?

**Comment by shiftlabs1** [comment] 2022-06-11 13:16
https://stackblitz.com/edit/github-c6w3iu?file=src/pages/sign-up.vue @plmercereau

**Comment by plmercereau** [comment] 2022-06-11 20:41
Hello,
Could you see this project?
https://stackblitz.com/edit/github-c6w3iu-zouzx7?file=src/pages/sign-up.vue

What changed:
- use the latest version of the `@nhost/vue` package (in `package.json`, the `*` is chosen, but it is better to set it to a specific version, the latest being `0.2.0`). Related PR: https://github.com/nhost/nhost/pull/703
- correct the signUp options (please have a look at the comments and subscribe to the related PRs).

**Comment by plmercereau** [comment] 2022-07-15 11:09
no news, closing for now. It the problem still occurs let us know and we'll reopen the issue

**Closed by plmercereau** 2022-07-15 11:09 UTC
Labels: needs info, sdk
