### ISSUE TITLE
NhostNextProvider broken SSG(static site generation) on NextJS application

### ISSUE THREAD

**Issue by pumpkin46** [nhost/nhost#873] opened 2022-08-07 00:47 UTC
I'm trying to use NhostNextProvider on NextJS application.
But once I used the provider, SSG is not working at all.
If I remove it, then everything is fine.
How can I solve this?

![image](https://user-images.githubusercontent.com/73939762/183270444-767f1980-a0b9-4751-ab7b-5cd007dc8692.png)

**Comment by elitan** [comment] 2022-08-08 05:41
Is it the `NhostNextProvider` that is not working with SSG?

What's the error message?

How do you initialize the `nhost` instance in `src/constants/nhost`?

**Comment by simpson** [comment] 2022-08-08 11:39
@elitan 

we use "next build && next export" and after we made some changes to implement nhostnext and nhostapollo our build outputs aren't static

Working: https://c341871b.designed-platform.pages.dev/
Broken: https://6ce777d6.designed-platform.pages.dev/

When we replaced NhostApollo with the generic Apollo client we were able to get it to work again. It appears the NhostApollo only works with SSR mode.

**Comment by pumpkin46** [comment] 2022-08-08 11:42
Hi, @simpson That's right.
Seems NhostNextProvider doesn't work with it.

**Comment by pumpkin46** [comment] 2022-08-08 11:47
> 

There is no error message.
And next export completed.
But static pages are generated incorrectly.

![2022-08-08_14h45_56](https://user-images.githubusercontent.com/73939762/183411091-e8f0e332-69d7-49e3-900e-095146a448d2.png)

**Comment by szilarddoro** [comment] 2022-08-08 19:23
Hey! 👋 Thanks for your detailed bug reports.

I'll take a look at this issue later this week and maybe reach out to you to get more information if needed. Thank you for your patience. 🙏

**Comment by simpson** [comment] 2022-08-08 19:30
@szilarddoro here is how we temporarily solved it

``` import React from "react";
import { NhostNextProvider } from "@nhost/nextjs";
import { ToastContainer } from "react-toastify";
import { NhostApolloProvider } from "@nhost/react-apollo";
import RedirectMiddleware from "../src/middlewares/RedirectMiddleware";
import "../src/assets/sass/framework.sass";
import "react-toastify/dist/ReactToastify.css";
import "../src/assets/css/tailwind.css";
import "../src/assets/css/skeleton.css";
import { nhost } from "../src/constants/nhost";
import UserProfileContext from "../src/hooks/useUserProfile";
import { ApolloClient, ApolloProvider, createHttpLink, InMemoryCache, useApolloClient } from "@apollo/client";

function MyApp({ Component, pageProps }) {  
  const client = new ApolloClient({
    ssrMode: true,
    link: createHttpLink({
      uri: 'https://hovfgsbqgycnxrcmhgvq.nhost.run/v1/graphql',
      credentials: 'same-origin',      
    }),
    cache: new InMemoryCache(),
  });
  
  if(typeof window !== 'undefined') return (
     <NhostNextProvider nhost={nhost} initial={pageProps.nhostSession}>
      <NhostApolloProvider nhost={nhost}>
      <UserProfileContext>
      <RedirectMiddleware>
        <Component {...pageProps} />
        <ToastContainer
          position="bottom-center"
          autoClose={3000}
          hideProgressBar={true}
          closeButton={false}
        />
      </RedirectMiddleware>
    </UserProfileContext>
   </NhostApolloProvider> 
  </NhostNextProvider> 
  )

  return (
    <NhostNextProvider nhost={nhost} initial={pageProps.nhostSession}>
    <ApolloProvider client={client}>
    <UserProfileContext>
          <RedirectMiddleware>
            <Component {...pageProps} />
            <ToastContainer
              position="bottom-center"
              autoClose={3000}
              hideProgressBar={true}
              closeButton={false}
            />
          </RedirectMiddleware>        
          </UserProfileContext>
    </ApolloProvider>
    </NhostNextProvider>
  );
}

export default MyApp;
```

**Comment by GavanWilhite** [comment] 2022-08-09 17:56
Yeah this is a tough bug, and I don't think this is a trivial workaround from what I can see. It breaks our Open Graph implementation (social link previews) which we rely on pretty heavily.

**Comment by GavanWilhite** [comment] 2022-08-09 18:01
I don't know the full answer, but here's more context: https://github.com/vercel/next.js/discussions/12350

Basically there's something not being provided soon enough, and useState / useEffect is usually the culprit

**Comment by simpson** [comment] 2022-08-09 18:23
@GavanWilhite ya this is causing all kinds of really strange side effects

**Comment by szilarddoro** [comment] 2022-08-10 09:09
@pumpkin46  @simpson do you have a repo I can use to reproduce this issue? I used a bare minimum Next.js project with `NhostNextProvider` and `NhostApolloProvider` inside `_app` and only see statically generated pages.

**Comment by szilarddoro** [comment] 2022-08-10 09:44
I created a [repository](https://github.com/szilarddoro/nhost-nextjs-ssg) as a starting point for this conversation.

There are two routes fetching data from the server during build (check links to see the result):
- [`/users/mockapi`](https://nhost-nextjs-ssg.vercel.app/users/mockapi) uses the Fetch API in `getStaticProps` to fetch a list of users
- [`/users/nhost`](https://nhost-nextjs-ssg.vercel.app/users/nhost) uses the Nhost SDK (GraphQL) to fetch a list of users

The actual build output:
```
info  - Checking validity of types...
--
11:39:21.605 | info  - Creating an optimized production build...
11:39:36.399 | info  - Compiled successfully
11:39:36.399 | info  - Collecting page data...
11:39:41.248 | info  - Generating static pages (0/5)
11:39:41.328 | info  - Generating static pages (1/5)
11:39:41.339 | info  - Generating static pages (2/5)
11:39:41.348 | info  - Generating static pages (3/5)
11:39:42.018 | info  - Generating static pages (5/5)
11:39:42.028 | info  - Finalizing page optimization...
11:39:42.033 |  
11:39:42.060 | Page                                       Size     First Load JS
11:39:42.060 | ┌ ○ /                                      289 B           161 kB
11:39:42.060 | ├   /_app                                  0 B             161 kB
11:39:42.060 | ├ ○ /404                                   193 B           161 kB
11:39:42.061 | ├ ● /users/mockapi                         365 B           161 kB
11:39:42.061 | └ ● /users/nhost (766 ms)                  352 B           161 kB
11:39:42.061 | + First Load JS shared by all              161 kB
11:39:42.061 | ├ chunks/framework-1d23e0fb4601e56d.js   45 kB
11:39:42.061 | ├ chunks/main-c8650c219ef2eb46.js        28.7 kB
11:39:42.061 | ├ chunks/pages/_app-dc0f2a46dc819a74.js  86.4 kB
11:39:42.061 | ├ chunks/webpack-9b312e20a4e32339.js     836 B
11:39:42.062 | └ css/27d177a30947857b.css               194 B
11:39:42.062 |  
11:39:42.062 | ○  (Static)  automatically rendered as static HTML (uses no initial props)
11:39:42.063 | ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
```

What else should I add to the [reproduction repository](https://github.com/szilarddoro/nhost-nextjs-ssg)?

**Comment by GavanWilhite** [comment] 2022-09-01 22:36
Thanks for taking a look at this. 

(Please correct me if I'm wrong on any of this, I have a surface-level understanding of Next.JS)

So I downloaded your repo repository and it seems like a perfect reproduction. Basically when you right-click -> "View Page Source", "Statically Generated Home Page" is not present in the code. I believe this is the core issue, as for Open Graph tags to work, then need to be rendered early enough such that they would show up in "View Page Source".

As mentioned before, they were showing up there before integrating NhostNextProvider

**Comment by GavanWilhite** [comment] 2022-09-01 22:54
@szilarddoro 

I also just double checked, and yeah if you remove the providers from _app.tsx it then shows "Statically Generated Home Page" in "View Page Source"

**Comment by simpson** [comment] 2022-09-02 12:24
@szilarddoro @GavanWilhite it looks like you have a repo reproducing the problem, but if you want to check out our project let me know and I can add you to it.

**Comment by szilarddoro** [comment] 2022-09-02 14:03
Thank you for elaborating on this @GavanWilhite. The build output has certainly tricked me.

I can't tell you exactly when we can submit a fix for this issue, but this is surely something we want to have a look at in the near future.

cc. @plmercereau

**Comment by GavanWilhite** [comment] 2022-09-02 16:42
Sounds good @szilarddoro 

In the interest of time, I may be able to give you a head-start here based on what I've learned so far (again, please take what I say here with a grain of salt, I'm not a React expert).

https://github.com/nhost/nhost/blob/9c382a3773e2b6af5c3480fadb65d6ead75e27e0/packages/react-apollo/src/provider.tsx#L18

This line I believe is the proximate cause. Given that it's not returning any children, we are going to see an empty render on first call.

It's doing so because it may not have a client ready. I don't know if there's a way to get react to wait for this. 

I think order of preference for fixes is:

1. Find a way to get the `ApolloProvider` ready on first render. This will likely involve not using `useState`, as I believe the `setClient` call in `useEffect` makes it wait a frame.

2. Punt and just return the children directly on first frame. This will mean that usage of the provider will fail, and workarounds will probably be needed, but at least we can feasibly get opengraph tags in by grabbing data another way in getServerSideProps and continue to use the NhostApolloProvider elsewhere.

**Comment by GavanWilhite** [comment] 2022-09-20 14:59
@szilarddoro Can we get an ETA on this?

**Comment by szilarddoro** [comment] 2022-09-20 15:26
Hey @GavanWilhite! We have not made any progress on this since the last time we talked about the topic here.

We are currently quite busy with preparations for our Product Hunt launch, but I'll try to submit a fix for this problem very soon. Probably this weekend or early next week.

**Comment by GavanWilhite** [comment] 2022-09-24 18:00
It's possible this may also be relevant?

https://medium.com/@A__G__B/component-level-data-fetching-in-next-js-with-srr-8d35cdc5849e

**Closed** 2022-09-26 13:59 UTC
Labels: bug, next.js

**Comment by GavanWilhite** [comment] 2022-09-26 14:41
Thanks!! @szilarddoro

**Comment by szilarddoro** [comment] 2022-09-26 14:58
Please let me know if the issue persist so we can keep digging.
