### ISSUE TITLE
@nhost/react-urql package

### ISSUE THREAD

**Issue by akhil-naidu** [nhost/nhost#1050] opened 2022-10-19 09:35 UTC
Can we expect a package similar to `@nhost/react-apollo` for URQL?

I've seen this [repository](https://github.com/nhost/react-urql), but the `README.md` is not what I expect. But in fact, most of the configuration for the `@nost/react-urql` was ready.

**Comment by akhil-naidu** [comment] 2022-10-19 09:38
#271

**Comment by plmercereau** [comment] 2022-10-19 09:39
yes, duplicate of the above. closing

**Closed by plmercereau** 2022-10-19 09:39 UTC
