### ISSUE TITLE
The refresh token is invalidated when using multiple browser clients

### ISSUE THREAD

**Issue by noverby** [nhost/nhost#555] opened 2022-05-14 10:41 UTC
E.g when you open a new tab, it'll read nhostRefreshToken cookie and call /auth/token with it. 
This action invalidates the token, the new one is now stored in-memory (in interpreter.state.context.refreshToken) AND in nhostRefreshToken cookie.

Then you open a new tab which does the same. 
The cookie is not tied to the tab, so tab1's nhostRefreshToken cookie is updated, but interpreter.state.context.refreshToken in tab1 is now outdated. 
When you call auth.refreshSession() in tab1, it'll read the token from the state, but since tab2 invalidated it, it'll result in an error.

**Comment by noverby** [comment] 2022-05-23 12:58
Fixed by: https://github.com/nhost/hasura-auth/commit/7583997e45f323005a23f8b4b2aaa83ef27d3dea

**Comment by szilarddoro** [comment] 2022-05-30 09:21
I'm closing this issue, because it has been resolved.

See https://github.com/nhost/hasura-auth/commit/7583997e45f323005a23f8b4b2aaa83ef27d3dea for further information.

**Comment by szilarddoro** [comment] 2022-05-30 09:28
Reopening because the changes have not been deployed to the production environment yet.

**Comment by plmercereau** [comment] 2022-05-30 09:33
Will be available when [hasura-auth v0.8.0](https://github.com/nhost/hasura-auth/releases/tag/v0.8.0) will be deployed

**Comment by plmercereau** [comment] 2022-06-02 19:59
@noverby we released the new version, please let us know if it solved your problem

**Comment by plmercereau** [comment] 2022-06-24 09:16
no news. Closing for now, don't hesitate to give us feedback later if the problem is not solved

**Closed by plmercereau** 2022-06-24 09:16 UTC
Labels: needs info
