### ISSUE TITLE
Social Auth for React Native Expo Apps

### ISSUE THREAD

**Issue by andrisole92** [nhost/nhost#2431] opened 2023-12-23 04:05 UTC
### **Is your feature request related to a problem? Please describe.**
First of all I would want to say that I really like your product!

The problem I have is that I need a mobile app and social auth is crucial for the smooth onboarding process.

Currently, as far as I can see Nhost does not have neither social auth mechanism neither documentation for it.

### **Describe the solution you'd like**
Support social auth for react native and Expo projects.

Might work in conjunction with Expo auth packages. There should be a way to reuse Apple/Google token for Nauth.

### **Describe alternatives you've considered**
I have considered using SMS auth - but it will require users to enter phone number.

### **Additional context**
N/A

**Comment by dbarrosop** [comment] 2023-12-24 08:18
[From the documentation](https://docs.nhost.io/product/authentication#oauth-providers). Closing as I don't think there is anything to do here but feel free to reopen otherwise.

**Closed by dbarrosop** 2023-12-24 08:18 UTC
Labels: enhancement

**Comment by andrisole92** [comment] 2023-12-24 08:27
@dbarrosop I don’t understand why you closing it?

it does not work out-of-the-box for react-native Expo apps.

The documentation you mentioned is only suitable for web application and not mobile applications.

I want to use Nhost, but currently blocked due to lack of the react native integration or an api for using token obtained from mobile auth.

**Comment by andrisole92** [comment] 2023-12-24 08:38
It’s not completed by any means @dbarrosop

**Comment by dbarrosop** [comment] 2023-12-24 12:33
To clarfiy, the links I shared work on any kind of application; mobile, cli, web, backend, anything.

What we don't have is support for React Native in the React SDK but that doesn't mean that social login can't be implemented by yourself in react native, you will simply have to rely on the javascript client or even on the HTTP APIs themselves.

If what you want is for the React SDK to support React Native too then there is already an issue for that so I'd suggest you to subscribe to that issue to avoid duplicates; https://github.com/nhost/nhost/issues/2216

If the issue is about something completely different let me know and we can reopen.

**Comment by andrisole92** [comment] 2023-12-24 18:37
@dbarrosop it does not work in React Native Expo apps.

I am getting the same error as described in #2216.

It would be great if you added support for Expo apps.

Is there any way you can re-use the auth token retrieve from the third party plugin? https://docs.expo.dev/versions/latest/sdk/apple-authentication/
