### ISSUE TITLE
Send `options` to hasura-auth on signing in with a provider

### ISSUE THREAD

**Issue by regalstreak** [nhost/nhost#188] opened 2022-01-25 12:24 UTC
Currently we're not sending the `options` object to `hasura-auth` which makes it pointless to have the options object in the interface in `nhost-js`. Send the object correctly so we can have support for `redirectTo` and other options like `locale`, `allowedRoles`, `defaultRole`, etc

https://github.com/nhost/hasura-auth-js/blob/main/src/hasura-auth-client.ts#L211-L219

**Comment by ttiras** [comment] 2022-03-02 13:07
i can confirm that i have the same issue.

**Comment by ttiras** [comment] 2022-03-07 17:04
same here. payments are involved at my app too and having trouble for users loging in at checkout or at account page. This will fix the trouble easily. Thank you.

**Comment by elitan** [comment] 2022-03-14 08:43
WIP: https://github.com/nhost/hasura-auth/pull/108

**Comment by plmercereau** [comment] 2022-03-25 15:00
Hello,
Provider options are now available [in the SDK](https://github.com/nhost/nhost/blob/4ed626d5b5f461be60c583dcb8b660732f9ce716/packages/hasura-auth-js/src/hasura-auth-client.ts#L162), and in `hasura-auth` since `v0.4.0`. Hasura-auth v0.4 is not yet used in the Nhost cloud, but it should occur in the upcoming weeks.

**Comment by nunopato** [comment] 2022-04-26 11:33
@regalstreak this has been released to production so I am closing this issue.

**Closed by nunopato** 2022-04-26 11:33 UTC
Labels: enhancement, sdk
