### ISSUE TITLE
Error: No useable method found in ["native","idb","localstorage"]

### ISSUE THREAD

**Issue by fanr870606** [nhost/nhost#409] opened 2022-04-14 03:20 UTC
Hi, I'm using React Native (0.68.0), when I tried to create an instance of NhostClient I got the following error:

_**Error: No useable method found in ["native","idb","localstorage"]**_

```
  const nhost = new NhostClient({
    backendUrl: 'https://test.nhost.run',
    clientStorageType: "react-native",
    clientStorage: AsyncStorage,
  });
```

**Comment by oristian** [comment] 2022-04-21 07:54
I have this same issue and error message.  In App.jsx of my RN app passing AsyncStorage

**Comment by eekrain** [comment] 2022-04-21 08:05
I have tried in react native 0.66.2 and 0.68.1 and i also have this problem.

**Comment by plmercereau** [comment] 2022-04-21 20:23
Hello,
I couldn't reproduce with the latest `@nhost/nhost-js` version when using ExpoJs and RN `0.66.2`. Could you tell more about your environment?
Here is [a repo that works](https://github.com/plmercereau/nhost-js-expo-basic), would you mind having a look at it and tell what is different in your setup?
Thanks

**Comment by eekrain** [comment] 2022-05-14 17:03
Hi! I have tried to update all the nhost dependencies and this problem was gone. You can close this issue.

**Closed** 2022-05-14 17:59 UTC
Labels: needs info, sdk
