### ISSUE TITLE
add "IF NOT EXISTS" to migrations

### ISSUE THREAD

**Issue by mainstreetmark** [nhost/nhost#1649] opened 2023-02-21 19:18 UTC
Every so often, my local database gets out of sync with the hosted database.  It's not clear when or how this happens, but it's usually for projects that have been put to sleep.

Anyways, during the process of getting things back in sync, I find i'm adding `IF NOT EXISTS` to the up.sql's.  And I was wondering, why not make that a default feature of migrations.   Should it fail of the column is already there?

**Comment by elitan** [comment] 2023-02-22 17:36
I think you should try to find the root cause of why this is happening in the first place instead of adding `IF NOT EXISTS` to statements in migrations.

If you follow the correct migrations procedure, which is: developed locally, push code, and Nhost applies migrations, then this is not an issue.

I'll close this specific issue, because we won't add `IF NOT EXISTS` to migrations. But I encourage you to keep digging and find out the root cause of your problem. 

Once we know, or once you know how to reproduce this issue, please open a new issue, and we'll figure it out there. Sounds good?

**Closed by elitan** 2023-02-22 17:36 UTC
Labels: enhancement

**Comment by mainstreetmark** [comment] 2023-02-22 18:29
Sounds good.
