### ISSUE TITLE
Functions tab is missing in the Cloud

### ISSUE THREAD

**Issue by vipafattal** [nhost/nhost#1590] opened 2023-02-06 15:28 UTC
![image](https://user-images.githubusercontent.com/22567094/217013178-30130cff-2f30-4c29-bc70-279f0ba39cf3.png)

**Comment by vipafattal** [comment] 2023-02-08 02:02
Is this thing intended to happen cuz I can't find another way to check functions logs, thanks

**Comment by pkreipke** [comment] 2023-02-08 02:38
It's under Logs, using the filter.

**Comment by vipafattal** [comment] 2023-02-08 02:49
Well then this not good. It used to have separate tab and see all the functions with there url. Please is possible we get the old functions tab

**Comment by pkreipke** [comment] 2023-02-08 03:19
I'm just another user by I'm sure it was important to NHost to remove duplicate functionality in the dashboard and free up resources for critical development tasks elsewhere.

If you prefer the previous version you can add suggestions or comments to this issue where I also expressed a fondness for the earlier split: https://github.com/nhost/nhost/issues/1581 but I recognize the limited time available to do all the things NHost wants to.

In the mean time you could try some of the workarounds I mention there:
- focus on just Functions from the drop down, narrow your date/time filters.
- search the page by the path to your function: you'll note that the wrapper around each log message has your function's path in it

**Comment by elitan** [comment] 2023-02-09 07:28
Duplicate of https://github.com/nhost/nhost/issues/1581

**Closed by elitan** 2023-02-09 07:28 UTC
Labels: bug
