### ISSUE TITLE
XMLHttpRequest is not defined when using with Remix.run

### ISSUE THREAD

**Issue by tom555my** [nhost/nhost#209] opened 2022-02-16 11:32 UTC
# Description

I was using nhost js sdk in my `remix.run` app. When I was executing `nhost.auth.signIn` in the action function, which run in server-side, an error of `'XMLHttpRequest is not defined'` occurred.

# Code snippet

```typescript
export const action: ActionFunction = async ({ request }) => {
  const formData = await request.formData();

  const email = formData.get('email');
  const password = formData.get('password');

  const schema = Joi.object({
    email: Joi.string().required().email(),
    password: Joi.string().required(),
  });

  try {
    const value = await schema.validateAsync({ email, password });
    const { session, error } = await nhost.auth.signIn(value);

    console.log({ session, error });
    if (error) {
      return json(
        {
          error: error.message,
        },
        400
      );
    }

    return redirect('/auth/sign-in');
  } catch (error) {
    const err = error as ValidationError;
    return json(
      {
        error: err.details[0].message,
      },
      400
    );
  }
};
```

<img width="541" alt="image" src="https://user-images.githubusercontent.com/19559068/154256349-3e7876b1-fe40-4ad1-9fb3-6560dd622c4b.png">

**Comment by fungilation** [comment] 2022-02-21 23:18
Reproduced. For me, `XMLHttpRequest is not defined` error I hit from Hasura event triggered nhost function call.

Solution: Locking package dep to `"@nhost/nhost-js": "0.3.6"` avoids hitting the error on nhost deployed function call. It's not axios related as upgrading to 0.25 have no issue, only upgrading @nhost/nhost-js to 0.3.7 would hit the error.

**Comment by elitan** [comment] 2022-02-23 09:21
This might have been fixed with our PR yesterday: https://github.com/nhost/nhost/pull/225

Can you try the latest `@nhost/nhost-js@0.3.9`?

Just as a note, we do see some [other issues](https://discord.com/channels/552499021260914688/735876020355465367/945788379189104700) in the current version and we're actively working on it right now.

**Comment by plmercereau** [comment] 2022-03-28 10:30
Hello Tommy,
I can't reproduce with the latest version of `@nhost/nhost-js`.
Could you bump to the latest version, and if the problem still occurs, share a link to a remix project that recreates the problem?

**Comment by elitan** [comment] 2022-04-01 11:53
I'll close this issue for now as we can't reproduce it with the latest `@nhost/nhost-js` package. 

Let us know if this problem still occurs and we can open this issue again.

**Closed by elitan** 2022-04-01 11:53 UTC
Labels: sdk
