### ISSUE TITLE
Project related issue: Building canvas-based app: Having CORS issue

### ISSUE THREAD

**Issue by MelodicCrypter** [nhost/nhost#995] opened 2022-10-05 17:43 UTC
Hi, I'm building a canvas-based application using fabricJS. When I load images into the canvas from other websites it has no problem at all like Icons8, etc. But when I load images that I uploaded to Nhost's storage it will have some CORS issue.

I already get the public url of each uploaded images using:
`const publicUrl = nhost.storage.getPublicUrl({ fileId: '<File-ID>' })`

I already use and search every possible solution from fabricJS community, adding `{crossOrigin: "Anonymous"}`, etc.

Is there any setting I can set for **Access-Control-Allow-Origin** inside Nhost or Hasura? Or the bucket itself?

Error:
![Screen Shot 2022-10-06 at 1 36 31 AM](https://user-images.githubusercontent.com/18341500/194125722-73dabd6b-fa80-4142-b563-58258344cfd2.png)

**Comment by elitan** [comment] 2022-10-05 17:49
Would you mind sharing a working public URL here that we can test?

Also, how do you use the image in fabricJS? Mind sharing some example code?

**Comment by MelodicCrypter** [comment] 2022-10-05 18:05
@elitan thanks for the quick response. Planning to create a fiddle but since I can't also show the whole process, here are 2 methods I created whenever I will insert images into the canvas through fabricJS:

```
const addImgToCanvasUtil = (url) => {
		if (fabric && url) {
			new fabric.util.loadImage(
				url,
				(img) => {
					const loadedImg = new fabric.Image(img);
					loadedImg.scale(loadedImg.width > 2900 ? 0.04 : 0.15);
					loadedImg.set({
						id: nanoid(6),
						snapAngle: 45,
						snapThreshold: 10,
						clipPath: new fabric.Circle({
							radius:
								loadedImg.width > maxImageWidthForRadius
									? maxRadiusValue + maxRadiusValueLarge
									: maxRadiusValue,
							originX: 'center',
							originY: 'center',
							startAngle: 0,
							angle: Math.PI * 2,
						}),
					});
					canvas.add(loadedImg);
					canvas.centerObject(loadedImg);
					canvas.setActiveObject(loadedImg);
					canvas.renderAll();
					// save it
					// const _stringifiedCanvas = JSON.stringify(canvas.toJSON());
					// saveCanvas(_stringifiedCanvas);
					// side-effect
					// disableCanvasWrapZooming();
				},
				{ crossOrigin: 'anonymous' }
			);
		}
	};
```

and this one:

```
const addImgToCanvas = (url) => {
		if (fabric && url) {
			new fabric.Image.fromURL(
				url,
				(img) => {
					img.scale(img.width > 2900 ? 0.4 : 0.15);
					img.set({
						id: nanoid(6),
						snapAngle: 45,
						snapThreshold: 10,
						clipPath: new fabric.Circle({
							radius:
								img.width > maxImageWidthForRadius
									? maxRadiusValue + maxRadiusValueLarge
									: maxRadiusValue,
							originX: 'center',
							originY: 'center',
						}),
					});
					canvas.add(img);
					canvas.centerObject(img);
					canvas.setActiveObject(img);
					canvas.renderAll();
					// save it
					// const _stringifiedCanvas = JSON.stringify(canvas.toJSON());
					// saveCanvas(_stringifiedCanvas);
					// side-effect
					// disableCanvasWrapZooming();
				},
				{ crossOrigin: 'anonymous' }
			);
		}
	};
```

pardon the format, but that's some of the methods I use whenever inserting normal images like jpeg, png, to the canvas.

**Comment by elitan** [comment] 2022-10-05 18:10
Thanks for the info.

Maybe `Access-Control-Allowed-Origin` should be defined in `storage.buckets`.

Or, more generally, we could have a `headers` (`JSONB`) column in `storage.buckets` where developers can set custom headers for all files for a specific bucket.

**Comment by MelodicCrypter** [comment] 2022-10-05 18:14
Thanks as well. Yah, that would be really awesome!

**Comment by MelodicCrypter** [comment] 2022-10-06 03:42
@elitan @dbarrosop I appreciate all your work for Nhost. Everything is great about it especially with your latest improvements and updates. But, regarding my case, is there any chance this will be implemented this month? I know there are lots of process in order to implement a certain feature, but just hoping it might be just quick 🤞🏻. Coz, my client already wants this project to be deployed/finished. Thank you.

**Comment by MelodicCrypter** [comment] 2022-10-06 09:16
> @MelodicCrypter are you setting the `Origin` header? `hasura-storage` already sets the relevant CORS headers when needed.
> 
> A similar issue: [nhost/hasura-storage#74 (comment)](https://github.com/nhost/hasura-storage/issues/74#issuecomment-1124661447) For reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#the_http_request_headers

Thanks for it. I'm sorry if I'm not that knowledgeable pertaining to this. Can you elaborate more how to do this? Coz, basically when adding images into the canvas through fabricJS they have their own request method, you can check it here:

https://github.com/fabricjs/fabric.js/blob/0830cdb24cc3c2004f3885a40cc1c91542343240/dist/fabric.js#L3523

So what I did, to test your suggestion, hopefully I'm doing it correctly, is that I patched their library using PNPM patch, and inserted

`xhr.setRequestHeader('Origin', 'http://localhost:3000');`

on line 3545 inside their `request()` method and hard-coded localhost just to test. But when I do that it also spit some error **'Refused to set unsafe header "Origin"**'.

Thanks for the help. @dbarrosop  @elitan

**Comment by dbarrosop** [comment] 2022-10-06 11:52
I am afraid I don't know anything about fabric.js so I can't help you there. You can check the two links I shared before. On the first one you can see how the CORS related headers are being set correctly if the request includes the `Origin` header and on the second link you can read about CORS itself, in particular, notice the following statement:

> Note that in any access control request, the [Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin) header is always sent.

**Comment by MelodicCrypter** [comment] 2022-10-06 12:51
I see. But, I just don't quite get why the images returned from Icons8 through their API works properly inside the canvas. Like this one:

https://ouch-cdn2.icons8.com/kU5D5N_CuhLTaKG0_RnvD-aPLExtQtExNoktGkHXz2U/rs:fit:1157:912/czM6Ly9pY29uczgu/b3VjaC1wcm9kLmFz/c2V0cy9zdmcvMzAv/YTIzZmMzODUtNDg5/Ni00NGY3LWI5ZTMt/ZmU2M2E3ZThiOWQ3/LnN2Zw.png

that's one of the API's returned image, and when I add that to the canvas, there's no any CORS error.

But when I add from Nhost storage:

https://<mybackend>.storage.us-east-1.nhost.run/v1/files/2c78ac02-6581-47b3-b685-d03756a22c94

it triggers CORS error

**Comment by dbarrosop** [comment] 2022-10-06 12:57
Because they are not following the CORS specification. They are returning the control headers even though the request didn't include an `Origin` header.

**Comment by MelodicCrypter** [comment] 2022-10-06 13:18
I completely understand and agree with you. But flexibility is also vital. I guess, what @elitan suggested above is also ideal, especially for this type of use case.

**Comment by elitan** [comment] 2022-10-07 17:06
@MelodicCrypter What is the error message you're getting exactly? 

I tried myself to use Fabric.js and was able to add an image from Storage:

```html
<canvas id="canvas" width="300" height="300" style="border: 1px solid"></canvas>

<script
  src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/5.2.4/fabric.min.js"
  integrity="sha512-HkRNCiaZYxQAkHpLFYI90ObSzL0vaIXL8Xe3bM51vhdYI79RDFMLTAsmVH1xVPREmTlUWexgrQMk+c3RBTsLGw=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
></script>
<script>
  var canvas = new fabric.Canvas('canvas')

  const url =
    'https://absvxxnsesanljntvxui.storage.eu-central-1.nhost.run/v1/files/e407259e-848f-48b0-91cb-cceb511f0966'
  new fabric.util.loadImage(url, (img) => {
    const loadedImg = new fabric.Image(img)
    // loadedImg.scale(loadedImg.width > 2900 ? 0.04 : 0.15)
    canvas.add(loadedImg)
    canvas.centerObject(loadedImg)
    canvas.setActiveObject(loadedImg)
    canvas.renderAll()
  })
</script>

```

**Comment by MelodicCrypter** [comment] 2022-10-08 02:33
@elitan The error I got is the screenshot I sent in the first conversation above. Where did you run this code? Fiddle?

When developing locally:
- client is on http://localhost:3000
- hasura/nhost server is http://localhost:1337

I also tried deploying it:
- client is deployed in DigitalOcean, so it's already https based
- then server is your prod default

all resulting to CORS issue. When I was using Express js before I could easily setup CORS, but I don't know what's really going on here in this case. Maybe, based on what **dbarrosop** said, I guess, Fabric not setting Origin headers. A bit lost right now.

By the way, my client framework is SvelteKit.

I will try to use the version of Fabric you used here, coz mine is using 5.2.1, and yours is 5.2.4

**Comment by MelodicCrypter** [comment] 2022-10-08 02:41
@elitan I notice your using the `fabric.util.loadImage` method, that will work perfectly when adding images but when you export your canvas to real image like jpeg or png, the canvas would be tainted, meaning it will not allow you to export your canvas because of the CORS issue.

Please try adding image using this method `fabric.Image.fromURL` coz this will automatically spit out the error. This method is Fabric's main method adding images (url based).

The one you used, will allow you to add first, but you will not be able to export the canvas, which the most important aspect of my project.

**Comment by MelodicCrypter** [comment] 2022-10-08 03:42
Here is a Fiddle: https://jsfiddle.net/Melodic_Crypter/7j04t2ba/8/ still using v5.2.4

I added new url from storage and a url from Icons8 to test each. Please uncomment/comment each block to check each results. Thanks for your patience.

**Comment by MelodicCrypter** [comment] 2022-10-08 03:52
My last option for Nhost storage assets, for now, is maybe proxy. I will try to figure out this one to proxy the image if it comes from your storage. I'm still going to implement it. Still not sure how to do it the proxy flow.

**Comment by dbarrosop** [comment] 2022-10-08 10:34
The problem is your image. In your fiddle you have two images `url` and `newURL`, both using our storage. The image in `url` returns the error you mention but the one in `newUrl` works fine:

<img width="1150" alt="Screenshot 2022-10-08 at 12 33 26" src="https://user-images.githubusercontent.com/6246622/194703205-1a08230f-f4e4-4de5-841c-e384248f4400.png">

<img width="1128" alt="Screenshot 2022-10-08 at 12 33 40" src="https://user-images.githubusercontent.com/6246622/194703207-d341ed78-c90d-43cc-b5d1-9fc2638b0e6d.png">

So this doesn't seem to be a CORS problem.

**Comment by MelodicCrypter** [comment] 2022-10-08 14:19
I think this time, you're missing the point. I'm only using mobile right so I can't edit the fiddle. 

For simplicity sake, we can just use one image from storage. Coz in the current fiddle maybe it's a bit all over the place. I will update it and just use one image.

The main point is that each Fabric method acts differently. But I'm certain that the current error corresponds to CORS issue - pertaining with Fabric. 

Coz I can also confirm that all images from your storage does not produce CORS issue when used in image tags in normal applications. Cors only appears when used with Fabric.

**Comment by elitan** [comment] 2022-10-09 11:40
I can use both images in your [jsfiddle](https://jsfiddle.net/Melodic_Crypter/7j04t2ba/8/) without any errors.

See video:

https://user-images.githubusercontent.com/331818/194754885-825d09b4-2681-4243-bb1f-a34b2a4bcea1.mp4


Can you explain the steps to reproduce this error in the jsfiddle?

**Comment by MelodicCrypter** [comment] 2022-10-10 08:54
@elitan I confirm that it is working (_INSIDE THE FIDDLE_) for both images coming from Nhost storage and using the `fabric.Image.fromURL()` method. I really don't know what happened coz last time it was not working. Thanks for trying. I also confirm that it is working for both versions 5.2.1 and 5.2.4 - both worked inside the Fiddle.

Anyway, still, it is not working inside my real project application. Please see screenshot. App is using SvelteKit and hosted in DigitalOcean. I'll just solve this on my own coz I think it doesn't have to do with your storage settings at all. I really don't know why it is not working, but in Fiddle it is working. Maybe it is because of Vite, coz SvelteKit is using Vite. I don't know.  I also bumped my project's Fabric version to 5.2.4.

Thanks again.

![Screen Shot 2022-10-10 at 4 44 27 PM](https://user-images.githubusercontent.com/18341500/194829694-f0a7c80c-9271-431e-b6d1-65d7d74a6041.png)

**Comment by dbarrosop** [comment] 2022-10-10 09:06
Something I'd suggest you to try is running the following:

```
curl --output /dev/null -v -H "Origin: example.com" https://xcffducurpnshjgqihcv.storage.us-east-1.nhost.run/v1/files/b80478bd-8009-43b8-98fd-15347f78a31e
```

Replacing `example.com` with your origin to make sure you see the relevant headers (for instance, with example.com you should see in the output:

```
< access-control-allow-origin: example.com
< access-control-expose-headers: Content-Length,Content-Type,Cache-Control,Etag,Last-Modified,X-Error
```

If you are testing on a browser you can also go to developer tools -> Network, find the request to the storage there and see if the request includes the `Origin` header.

**Comment by MelodicCrypter** [comment] 2022-10-10 11:00
@dbarrosop I appreciate your help. Thanks. These are the results, I tested using Network tab:

Setup:
- Chrome, latest version
- SvelteKit (Svelte) framework
- Hosted in DigitalOcean

Application flow:
- when the app loads, all the images from Nhost storage that user owns are loaded
- so when loaded, there are no cors issues or anything, all file urls are injected to the DOM each IMG tags
- when user clicks an image (hosted from Nhost storage or not) it should be added to the canvas (Fabric)

Test flow:
- after images were loaded
- I tried clicking an image
- screenshots below are the same image file, first successfully loaded to the DOM, but when clicked, that's when issue occurs

1 IMAGE - LOADED INTO THE DOM WITHOUT ANY ISSUES
![no-cors-issue](https://user-images.githubusercontent.com/18341500/194850686-a208f984-7db8-4c9b-94e0-fc6f417d0164.png)


2 IMAGE - ALREADY LOADED INTO THE DOM, BUT WHEN INJECTED TO THE FABRIC CANVAS, HAS ISSUE
![has-cors-issue](https://user-images.githubusercontent.com/18341500/194851084-072954f5-ef16-48d5-a58b-4d76d8249faa.png)

**Comment by dbarrosop** [comment] 2022-10-12 05:40
Have you figured this one out? I am happy to help but without a way of reproducing I feel like there isn't much more I can do. However, by the looks of it, if looks like something is interfering with the CORS headers; the origin header is in the request and the response header has `access-control-expose-headers` but I can't see the `access-control-allow-origin`, which is extremely strange as the server adds both as you can see if you query yourself the server with curl so something must be removing it.

**Comment by oriollpz** [comment] 2023-04-15 17:31
I have the same issue, how can I fix it?

**Comment by dbarrosop** [comment] 2023-04-16 11:40
@oriollpz please, open a new issue and describe your problem and detailed steps to reproduce thanks.

I am closing this issue as this wasn't a problem on hasura-storage to the best of our knowledge.

**Closed by dbarrosop** 2023-04-16 11:40 UTC
Labels: storage
