### ISSUE TITLE
ReferenceError: React is not defined 

### ISSUE THREAD

**Issue by kelkes** [nhost/nhost#1927] opened 2023-05-13 10:08 UTC
**Describe the bug**
After updating to `@nhost/nextjs` Verison 1.13.22 i get `ReferenceError: React is not defined` after starting up my next.js based app. When downgrading to 1.13.21 it works.

**To Reproduce**
1. update nhost/nextjs version to 1.13.22
2. run `next dev`
3. login to my app
4. error is shown.

The page is guarded with

```
import type {NextPage} from 'next';
import {useRouter} from 'next/router';
import {useAuthenticationStatus, SignedIn} from '@nhost/nextjs';
import {Spinner} from '@chakra-ui/react';

export function authProtected<T>(Comp: NextPage<T>) {
    return function AuthProtected(props: T) {
        const router = useRouter();
        const {isLoading, isAuthenticated} = useAuthenticationStatus();

        if (isLoading) {
            return <Spinner />;
        }

        if (!isAuthenticated) {
            router.push(`/sign-in?rd=${encodeURIComponent(router.asPath)}`);
            return null;
        }

        return (
            <SignedIn>
                <Comp {...props} />
            </SignedIn>
        );
    };
}
```

and the `getServerSideProps` is fairly basic like this:

```
export const getServerSideProps: GetServerSideProps<IndexPageProps> = async (
    ctx
) => {
    const nhostSession = await getNhostSession(
        {
            subdomain: process.env.NEXT_PUBLIC_NHOST_SUBDOMAIN,
            region: process.env.NEXT_PUBLIC_NHOST_REGION,
        },
        ctx
    );

    return {
        props: {
            nhostSession,
        },
    };
};
```

The app itself is done following the nhost/nextjs documentation.

**Expected behavior**
The app should run like with 1.13.21

**Screenshots**
<img width="1038" alt="SCR-20230513-kwft" src="https://github.com/nhost/nhost/assets/204445/69801e16-5c4e-45ef-8c98-269244aeeb0d">

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.3.1 (Air M2)
 - Browser chrome
 - Version [Version 113.0.5672.92

**Additional context**
I can provide access to the app repository too.

**Comment by szilarddoro** [comment] 2023-05-15 06:57
I'll close this because it is a duplicate of #1914. Could you please create a minimal reproducible example and share it on the other issue?

**Closed by szilarddoro** 2023-05-15 06:57 UTC
Labels: bug
