### ISSUE TITLE
Fails to link existing remote app with local environment

### ISSUE THREAD

**Issue by seyaobey-dev** [nhost/nhost#854] opened 2022-07-25 16:48 UTC
I am attempting to link my remote app with a local environment by running 
```
nhost init --remote -n my-nhost-app
```
Then I ran `nhost dev` (clean docker install). The local console app starts with an error:
```
GraphQL Engine metadata is inconsistent with database
```
From the error page, it looks like the issue is with `computed_fields`. 

`version: Nhost CLI v0.6.12 for darwin-arm64`

Here is the screenshot of the full error page:

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/83374925/180831769-e75c8d61-ea83-4dc7-8394-1895094b7a05.png">

**Comment by elitan** [comment] 2022-08-01 05:58
This seems to be an issue specifically with **computed fields**. Do you have an example table with computed fields we can use to reproduce this bug?

**Comment by seyaobey-dev** [comment] 2022-08-01 10:52
@elitan I have a couple of tables in my app with computed fields. I have added you as a member to my workspace https://app.nhost.io/viva. The specific project is `vivamosolo-nhost-dev`. And the tables are:
`group` and `member`.
Let me know if you need anything for better debugging

**Comment by nunopato** [comment] 2022-08-04 02:25
@seyaobey-dev I was able to reproduce your problem and found out that the functions used by all computed fields are not being included in the migration files generated by pg_dump. It should be safe for you to ignore those inconsistencies (but don't delete them) if you don't need to change those functions for now. In the meantime, we will work on a fix. Thank you for reporting!

**Comment by nunopato** [comment] 2022-10-05 18:56
@seyaobey-dev sorry for only now circling back, but this issue should be fixed in the latest release of the CLI. Do you confirm?

**Comment by elitan** [comment] 2022-11-20 19:03
We've done significant updates to the CLI, so this issue _should_ have been fixed now. If anyone has issues with linking an existing app and computed fields, please write a comment with a description, and we can re-open this issue.

**Closed by elitan** 2022-11-20 19:03 UTC
Labels: bug, needs info
