### ISSUE TITLE
Error: unknown flag: --project-directory

### ISSUE THREAD

**Issue by awidjaja** [nhost/nhost#2121] opened 2023-07-15 14:29 UTC
**Describe the bug**
nhost up doesn't work with Podman

**To Reproduce**
1. nhost init
2. nhost up
`Error: unknown flag: --project-directory`

**Expected behavior**
```bash
Nhost development environment started.

URLs:
- Postgres:             postgres://postgres:postgres@localhost:5432/local
- Hasura:               https://local.hasura.nhost.run
- GraphQL:              https://local.graphql.nhost.run
- Auth:                 https://local.auth.nhost.run
- Storage:              https://local.storage.nhost.run
- Functions:            https://local.functions.nhost.run
- Dashboard:            https://local.dashboard.nhost.run
- Mailhog:              https://local.mailhog.nhost.run

SDK Configuration:
 Subdomain:             local
 Region:                (empty)

Run `nhost up` to reload the development environment
Run `nhost down` to stop the development environment
Run `nhost logs` to watch the logs
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 (WSL)
 - Browser: chrome
 - Version: 114.0.5735.199 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
Many developers use podman as replacement for docker (the same docker command works, except few parameters). There is a separate podman-compose program that can make podman to spin up containers from docker-compose.yaml file. Podman can also spin up containers from kubernetes yaml file (in a pod).

**Comment by dbarrosop** [comment] 2023-07-16 08:31
Thanks for reporting. I am closing as duplicate of nhost/cli#727

**Closed by dbarrosop** 2023-07-16 08:31 UTC
Labels: bug
