### ISSUE TITLE
500 responses when trying create users 

### ISSUE THREAD

**Issue by ejkkan** [nhost/nhost#1224] opened 2022-11-27 14:59 UTC
Steps before project started to act up.
1. I created a new free project.
2. created a new user.
3. removed the user
4. Not I can't create new users via nhost ui or my own applicaton.

response `{"error": "network", "message": "Request failed with status code 500", "status": 500}`

**Comment by elitan** [comment] 2022-12-19 07:09
Probably some local bug. I can't reproduce. I'm closing this for now.

**Closed by elitan** 2022-12-19 07:09 UTC
Labels: bug
