### ISSUE TITLE
The "check all" checkbox on the Database view doesn't check all

### ISSUE THREAD

**Issue by mainstreetmark** [nhost/nhost#2526] opened 2024-02-09 13:26 UTC
On the Dashboard->Database view, there is a checkbox on top of the column of checkboxes.

The expected behavior is that clicking that checkbox will toggle all the checkboxes in the view, like for bulk deleting.  However, clicking on that checkbox does nothing at all.  

![image](https://github.com/nhost/nhost/assets/7000335/945eda69-6253-48e2-b583-92ea20947bea)

For reference, Hasura has the same checkbox, and works as expected.

(this is on app.nhost.io)

**Comment by dbarrosop** [comment] 2024-02-09 14:14
Do you have a connected repository? If you do, this is a duplicate of https://github.com/nhost/nhost/issues/2476

**Comment by mainstreetmark** [comment] 2024-02-09 14:17
yep.  ok.

**Comment by dbarrosop** [comment] 2024-02-09 14:42
Ok, closing this one then. Feel free to follow the other one which should be addressed in a couple of weeks. Thanks!

**Comment by dbarrosop** [comment] 2024-02-19 11:33
Turns out it is related but it's not the same issue so we are reopening.

**Closed** 2024-02-19 16:31 UTC
Labels: bug
