### ISSUE TITLE
Unable to signin using nhost auth

### ISSUE THREAD

**Issue by Kaijonsson** [nhost/nhost#2579] opened 2024-03-03 07:05 UTC
I'm not able to sign in with social login.
This is the error:

" ERROR  [TypeError: Cannot set property 'href' of undefined]"

I'm running:
     "@nhost/react": "^3.2.2"
    "react-native": "0.73.5",

This is how i initiate nhost:

nhost/config/config.ts:

```
import {NHOST_REGION, NHOST_SUBDOMAIN} from '@env';
import {NhostClient} from '@nhost/react';

export const nhost = new NhostClient({
  subdomain: NHOST_SUBDOMAIN,
  region: NHOST_REGION,
});

```

App.tsx:

```
    <NhostProvider nhost={nhost}>
      <RecoilRoot>
        <NavigationContainer theme={THEME}>
          <SafeAreaProvider>
            <StatusBar barStyle="dark-content" />
            <AppStack />
          </SafeAreaProvider>
        </NavigationContainer>
      </RecoilRoot>
    </NhostProvider>
```

And the login screen wher ei try to get it going:

```
import {nhost} from '@lib/nhost/nhost.config';
import {Col, Text} from '@ui/index';
import React, {useEffect} from 'react';

export const LoginScreen = () => {
  useEffect(() => {
    console.log('heeeloooo');
    (async () => {
      try {
        await nhost.auth.signIn({
          provider: 'google',
        });
      } catch (e) {
        console.error(e);
      }
    })();
  }, []);
  return (
    <Col flex justifyContent="center" alignItems="center">
      <Text textStyle="title2" emphasized>
        Login
      </Text>
    </Col>
  );
};

```

I have followed the tutorial:

https://docs.nhost.io/guides/auth/social/sign-in-google

Hope u can see what i'm doing wrong.
//Axel

**Comment by dbarrosop** [comment] 2024-03-03 08:20
Hi, our SDK is for react, not for react native. We have plans to add compatibility soon-ish though (~2 months). In the meantime you can use the javascript SDK directly.

I am closing as duplicate of https://github.com/nhost/nhost/issues/2216 , feel free to subscribe to the other issue for updates.

**Closed by dbarrosop** 2024-03-03 08:20 UTC
