### ISSUE TITLE
Social Auth: `redirectTo` not working

### ISSUE THREAD

**Issue by mrinalwahal** [nhost/nhost#234] opened 2022-03-01 09:53 UTC
Opening this issue as a follow up on a short discussion I had with @elitan regarding the same.

I have a dynamic route `/posts/:id`, where `id` changes dynamically. I want to redirect back to the same route after social provider login, but the `redirectTo` option is not working in the SDK.

Roughly what I'm attempting:

```
$nhost.auth.signIn({
  provider: 'google',
  options: {
    redirectTo: '/posts/' + id,
  }})
```

I always get redirected to the baseURL i.e. `/` for local, and `https://xxx.com` for production.

I can confirm the SDK has support for `redirectTo` option in social login. Over [here](https://github.com/nhost/nhost/blob/main/packages/hasura-auth-js/src/utils/types.ts#L97).

**Comment by elitan** [comment] 2022-03-01 10:08
You need to specify the full URL in the `redirectTo` option/.

I would recommend using environment variables to differentiate between local and prod environments for the base URL. Like this:

(untested code)


```js
const baseUrl = process.env.ENV === 'production' : 'https://example.com' : 'http://localhost:3000';

const redirectTo = `${baseUrl}/post/${id}`;

nhost.auth.signIn({
  provider: 'google',
  options: {
    redirectTo: redirectTo,
  }})
```

Would that fix your issue?

**Comment by mrinalwahal** [comment] 2022-03-01 10:27
It's not working.

And as far as I can see in the callback URL the SDK is redirecting me to, doesn't even contain the manually specified redirection URL. But I'm not sure if it has to.

`https://accounts.google.com/o/oauth2/v2/auth/oauthchooseaccount?access_type=offline&prompt=consent&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A1337%2Fv1%2Fauth%2Fsignin%2Fprovider%2Fgoogle%2Fcallback&scope=email%20profile&state=32d85d9d-88e3-4600-ba72-90d7e22a3bf8&client_id=800209053143-qgeoo16ajoaugrs4sk8qban8gmg31odr.apps.googleusercontent.com&flowName=GeneralOAuthFlow`

**Comment by elitan** [comment] 2022-03-01 10:40
> It's not working.
What is not working? What error do you get?

> But I'm not sure if it has to.
No. It does not have to. The redirect URL is saved in the database. We're using the `state` parameter to keep track of requests.

> Do I have to add anything to the allowed_redirect_urls variable in config.yaml?
The redirect URL must start with either the value of `AUTH_CLIENT_URL` or one of the URLS in the `AUTH_ALLOWED_REDIRECT_URLS`.

To help you further:

- Again: What is not working? What error do you get?
- What's the value of `auth_client_url` in your config.yaml? 
- What's the exact URL you pass to `redirectTo`? 
- Do you see the request being saved in `auth.provider_request` table in the database after you've issued `nhost.auth.signIn(..)`?

**Comment by mrinalwahal** [comment] 2022-03-01 10:44
There is no error. I just get redirect to the base client URL. Not the redirection route I'm passing in `redirectTo` parameter.

Also, I don't see `redirectTo` URL being read over [here](https://github.com/nhost/nhost/blob/9f4c44cc04c0055bc215190dc0f077d3bf7865f1/packages/hasura-auth-js/src/hasura-auth-client.ts#L215). Is that a problem? Only the provider URL is being read.

**Comment by elitan** [comment] 2022-03-01 20:50
Ok, thanks for the details. I'll test this on my end and get back to you here.

> Also, I don't see redirectTo URL being read over [here](https://github.com/nhost/nhost/blob/9f4c44cc04c0055bc215190dc0f077d3bf7865f1/packages/hasura-auth-js/src/hasura-auth-client.ts#L215). Is that a problem? Only the provider URL is being read.

It's in the `params` here: https://github.com/nhost/nhost/blob/9f4c44cc04c0055bc215190dc0f077d3bf7865f1/packages/hasura-auth-js/src/utils/types.ts#L97

**Comment by plmercereau** [comment] 2022-03-02 09:52
Duplicate of #188

**Closed by plmercereau** 2022-03-02 09:52 UTC
