### ISSUE TITLE
Self-hosting 404

### ISSUE THREAD

**Issue by jaty613** [nhost/nhost#859] opened 2022-07-28 04:25 UTC
docker ps -a

CONTAINER ID   IMAGE                                      COMMAND                  CREATED          STATUS                    PORTS                                                                                          NAMES
ace4998ab14d   nhost/hasura-storage:0.2.1                 "/nix/store/vzi4jq6m…"   18 minutes ago   Up 8 minutes              8000/tcp                                                                                       docker-compose_storage_1
dc7a3326d1d3   nhost/hasura-auth:latest                   "docker-entrypoint.s…"   18 minutes ago   Up 8 minutes              4000/tcp                                                                                       docker-compose_auth_1
72b6b18a567c   hasura/graphql-engine:v2.2.0               "graphql-engine serve"   18 minutes ago   Up 8 minutes              8080/tcp                                                                                       docker-compose_graphql-engine_1
1be8d663535d   traefik:v2.5                               "/entrypoint.sh --ap…"   18 minutes ago   Up 8 minutes              80/tcp, 0.0.0.0:1337->1337/tcp, :::1337->1337/tcp, 0.0.0.0:9090->8080/tcp, :::9090->8080/tcp   traefik
42561abbf941   minio/minio:RELEASE.2021-09-24T00-24-24Z   "sh -c 'mkdir -p /da…"   18 minutes ago   Up 8 minutes              0.0.0.0:8484->8484/tcp, :::8484->8484/tcp, 9000/tcp                                            docker-compose_minio_1
78f047ac918e   postgres                                   "docker-entrypoint.s…"   18 minutes ago   Up 8 minutes              0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                                      docker-compose_postgres_1
c15c49adb0fa   nhost/functions:latest                     "docker-entrypoint.s…"   18 minutes ago   Up 8 minutes              3000/tcp                                                                                       docker-compose_functions_1
e9df8b5994da   mailhog/mailhog                            "MailHog"                18 minutes ago   Up 8 minutes              0.0.0.0:1025->1025/tcp, :::1025->1025/tcp, 0.0.0.0:8025->8025/tcp, :::8025->8025/tcp           docker-compose_mailhog_1

--------------------------
http://localhost:1337
404 page not found

-------------------------
ubuntu@docker:~/nhost/examples/docker-compose$ cat .env
POSTGRES_PASSWORD=secret-pg-password-never-use-this-value
HASURA_GRAPHQL_ADMIN_SECRET=hello123
HASURA_GRAPHQL_JWT_SECRET='{"type":"HS256", "key":"5152fa850c02dc222631cca898ed1485821a70912a6e3649c49076912daa3b62182ba013315915d64f40cddfbb8b58eb5bd11ba225336a6af45bbae07ca873f3","issuer":"hasura-auth"}'
STORAGE_ACCESS_KEY=storage-access-key-never-use-this-value
STORAGE_SECRET_KEY=storage-secret-key-never-use-this-value

**Comment by elitan** [comment] 2022-08-02 18:44
Could you paste your docker-compose file too?

Also, would be great if you wrap your code in ```

**Comment by strefethen** [comment] 2022-09-16 17:20
I just cloned the repo and followed the exact instructions in the README.md and have the same result. As I watch the console output I see a recurring error with postgres:

```
 | 2022-09-16 17:19:13.843 UTC [62] FATAL:  password authentication failed for user "postgres"
postgres_1        | 2022-09-16 17:19:13.843 UTC [62] DETAIL:  Connection matched pg_hba.conf line 100: "host all all
```

**Comment by plmercereau** [comment] 2022-09-16 17:27
you mean when using  the [docker-compose example](https://github.com/nhost/nhost/tree/main/examples/docker-compose)?

I can't reproduce. I suggest you remove the `data` directory if it already exists.

**Comment by strefethen** [comment] 2022-09-16 19:07
@plmercereau I hate to say it but there's something a little random here.

I literally followed the exact instructions from the README and got a 404. Following your post above, I looked and there was a `data` folder so I deleted it then re-ran `docker-compose up` and can browse to http://localhost:1337 without issue.

Ok, I then deleted the entire repo folder and started over, and I now see JWT error that occurs dozens of times as docker is starting and I'm back to the 404. Deleting the `data` folder does NOT fix the problem. I've tried doing that three times now and I can't get the stack to stand up.

See the last line of the above output is the error I see dozens of times in the output. 

Following that, if I exit `docker-compose` and delete the `data` folder, same problem.

I did have it working once and got to the Haura login prompt. Can't seem to get back there now. 

I'm on MBP M1.

```
➜  github rm -rf nhost
➜  github git clone https://github.com/nhost/nhost.git
Cloning into 'nhost'...
remote: Enumerating objects: 26772, done.
remote: Counting objects: 100% (3103/3103), done.
remote: Compressing objects: 100% (973/973), done.
remote: Total 26772 (delta 2115), reused 3017 (delta 2068), pack-reused 23669
Receiving objects: 100% (26772/26772), 86.52 MiB | 14.68 MiB/s, done.
Resolving deltas: 100% (18103/18103), done.
➜  github cd docker-compose
cd: no such file or directory: docker-compose
➜  github rm -rf nhost
➜  github git clone https://github.com/nhost/nhost.git
Cloning into 'nhost'...
remote: Enumerating objects: 26772, done.
remote: Counting objects: 100% (3103/3103), done.
remote: Compressing objects: 100% (973/973), done.
remote: Total 26772 (delta 2115), reused 3017 (delta 2068), pack-reused 23669
Receiving objects: 100% (26772/26772), 86.52 MiB | 39.34 MiB/s, done.
Resolving deltas: 100% (18103/18103), done.
➜  github cd nhost/examples/docker-compose
➜  docker-compose git:(main) docker-compose up
WARNING: The HASURA_GRAPHQL_JWT_SECRET variable is not set. Defaulting to a blank string.
WARNING: The HASURA_GRAPHQL_ADMIN_SECRET variable is not set. Defaulting to a blank string.
WARNING: The STORAGE_ACCESS_KEY variable is not set. Defaulting to a blank string.
WARNING: The STORAGE_SECRET_KEY variable is not set. Defaulting to a blank string.
Starting docker-compose_functions_1  ... done
Starting traefik                     ... done
Recreating docker-compose_postgres_1 ... done
Starting docker-compose_mailhog_1    ... done
Recreating docker-compose_minio_1    ... done
Recreating docker-compose_graphql-engine_1 ... done
Recreating docker-compose_auth_1           ... done
Recreating docker-compose_storage_1        ... done
Attaching to traefik, docker-compose_mailhog_1, docker-compose_minio_1, docker-compose_functions_1, docker-compose_postgres_1, docker-compose_graphql-engine_1, docker-compose_storage_1, docker-compose_auth_1
functions_1       | [nodemon] 2.0.19
functions_1       | [nodemon] to restart at any time, enter `rs`
functions_1       | [nodemon] watching path(s): *.*
functions_1       | [nodemon] watching extensions: json,yaml,lock
functions_1       | [nodemon] starting `cd $FUNCTIONS_WORKING_DIR ; ni ; nodemon --ext 'js,ts' -w $FUNCTIONS_RELATIVE_PATH -x 'tsx' $SERVER_PATH/server.ts ./functions/package.json`
graphql-engine_1  | Fatal Error:- Environment variable HASURA_GRAPHQL_JWT_SECRET: Error in $: not enough input
```

**Comment by strefethen** [comment] 2022-09-16 19:19
Btw, the first time I tried I got this postgres error:

```
postgres_1        | 2022-09-16 17:15:00.143 UTC [33] FATAL:  password authentication failed for user "postgres"
```

The second time I saw this JWT error:

```
graphql-engine_1  | Fatal Error:- Environment variable HASURA_GRAPHQL_JWT_SECRET: Error in $: not enough input
```

I tried reproducing the first one and I can't. The second one occurs if you don't copy the .env file.

**Comment by plmercereau** [comment] 2022-09-16 20:53
> NM, I forgot to copy the .env, after that it worked.

great news :)
my 2 cents about your last comment:


> ```
> postgres_1        | 2022-09-16 17:15:00.143 UTC [33] FATAL:  password authentication failed for user "postgres"
> ```

the postgres data volume may have been initiated when no env var were set - hence with a password defaulting to `secretpgpassword`. The default pg password in `.env.example` is `secret-pg-password-never-use-this-value` and cannot then access to the DB. And vice versa.

Closing for now, good luck for what's next!

**Closed by plmercereau** 2022-09-16 20:53 UTC
Labels: needs info
