### ISSUE TITLE
Apollo doesn't re-render items with same __typename and same id

### ISSUE THREAD

**Issue by fabioespinosa** [nhost/nhost#182] opened 2021-09-24 21:32 UTC
When working with Apollo when an item of the same ___typename_ and same _id_ came after a mutation, everything changed in the cache and therefore one didn't need to do any refetchQueries, and data from queries where these items where fetched would re-render automatically.

However, when using this package after mutating or creating a new item, I can see that the item is in the cache (by looking at apollo devtools) but the lists where these items are queried do not re-render automatically.

I wonder if there is a setting somewhere to enable this behavior.

**Comment by plmercereau** [comment] 2022-04-01 18:14
Hello, 
Thanks for this issue.
Can't reproduce with the latest version of react-apollo. Closing it for now, don't hesitate to reopen it the problem still occurs, preferably with more context so we can reproduce

**Closed by plmercereau** 2022-04-01 18:14 UTC
Labels: sdk
