### ISSUE TITLE
Getting Warning useLayoutEffect after upgrading to React 18 and most recent @Nhost/nextjs and @Nhost/react versions

### ISSUE THREAD

**Issue by alveshelio** [nhost/nhost#521] opened 2022-05-06 14:54 UTC
Hi,

I'm getting this warning in server side
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at jd (/Users/helio/Development/work/avansai/avansai-app/web/node_modules/@nhost/react/dist/index.umd.js:66:676)

**Comment by szilarddoro** [comment] 2022-05-06 15:27
Hey @alveshelio. This is a duplicate of https://github.com/nhost/nhost/issues/447. I'm going to close this issue. We will release a new version of our `@nhost/react` package very soon that will fix this issue.

**Closed by szilarddoro** 2022-05-06 15:27 UTC
