### ISSUE TITLE
nhost/react module not loading in ReactNative 0.7 

### ISSUE THREAD

**Issue by lachu97** [nhost/nhost#1623] opened 2023-02-17 04:10 UTC
I use "@nhost/react": "^1.13.4", library for my New React Native Project(version:0.71.3) while the android build is successful but in the metro Bundler iam getting the below error
![errors](https://user-images.githubusercontent.com/49357162/219546515-dddb1c41-223a-4c94-ab42-1a52487167b0.png)

**To Reproduce**
1. Make a New React native Project 
2. Then Run npm install @nhost/react library package 
3. In app.js file add NhostProvider as your root component and run it

**Expected behavior**
I want app to run properly 

**Desktop (please complete the following information):**
 - OS: Window 10
 - Android Phone Pixel 6

**Smartphone (please complete the following information):**
 - Device:Pixel 6
 - OS:Android 11
If I remove the nhost library its working properly.

**Comment by beepsoft** [comment] 2023-02-17 13:09
The same with RN/Expo: https://github.com/nhost/nhost/issues/1607

**Comment by lachu97** [comment] 2023-02-18 16:32
Ok but that's not a good fix, i guess there's a problem with the nhost/react module.Downvaluing ES version not comfortable in a very large codebase

**Comment by beepsoft** [comment] 2023-02-18 19:02
@lachu97 Yes, you are right. There are 2 problems currently with the nhost sdk. One is related to react native web (my patch solves that hopefully) and the other one is related to the way axios is used by the sdk.

**Comment by lachu97** [comment] 2023-02-18 20:42
@beepsoft Thanks hopefully it runs properly in the next version.

**Comment by szilarddoro** [comment] 2023-02-19 11:33
Hey @lachu97! I'm working on a fix that'll solve the issue you are experiencing. It is most likely related to Axios. Hopefully we can release that fix in the beginning of next week.

**Comment by szilarddoro** [comment] 2023-02-20 08:10
A quick follow-up on this one. We plan to release a new major version at the end of this month / the beginning of March, eliminating Axios. This means the fix will be delayed a little bit because my change would cause conflicts with https://github.com/nhost/nhost/pull/1348. Let's come back to this in a few days.

**Comment by szilarddoro** [comment] 2023-02-23 11:05
The new version without Axios has been released. Could you folks please give it a shot?

**Comment by beepsoft** [comment] 2023-02-23 11:53
Yes! 🥳  I can confirm that with `"@nhost/nhost-js": "^2.0.2"` it works on iOS.

However it still fails with RN web like here: https://github.com/nhost/nhost/issues/1607

**Comment by lachu97** [comment] 2023-02-25 15:26
HI @beepsoft I tried to run with the new version of nhost/react:2.0.3, its working fine but not able to signIn or Login using those hooks provided with the library.Throws network error with error code of 0.

**Comment by szilarddoro** [comment] 2023-02-27 08:17
@lachu97 just a few follow-up questions

- Are you connecting to the Nhost project that is running locally through the CLI?
- Are you running your project on your device or through an emulator?

**Comment by lachu97** [comment] 2023-03-03 15:12
I actually used a real Android device not an emulator,and in nhost Dashboard using a live project with subdomain and region.Yet no luck,still throws Network Error

**Comment by szilarddoro** [comment] 2023-03-06 16:28
That's most likely because your device doesn't see the Nhost CLI running on your machine because it's only exposed on `localhost`. Unfortunately, this is not something we can fix in the SDK. I'll add @elephant3 to this conversation. Maybe he has some ideas for this one.

**Comment by szilarddoro** [comment] 2023-03-22 12:17
I'll close this issue as the original problem has been solved. Feel free to open a new one with the other problem if it persists.

**Closed by szilarddoro** 2023-03-22 12:17 UTC
Labels: bug, sdk
