### ISSUE TITLE
Latest Packages cause error on NPM install 

### ISSUE THREAD

**Issue by ArieJones** [nhost/nhost#326] opened 2022-04-01 23:58 UTC
Appears if I cannot update to the newest @nhost/nextjs package because of the following error 

Unsupported URL Type "workspace:": workspace:^

Looks like the same is true for nhost-js react react-apollo  packages as well

logs look pretty similar to this one trying to install @nhost/react@0.4.1 

```30 silly idealTree buildDeps
31 silly fetch manifest @nhost/react@0.4.1
32 timing arborist:ctor Completed in 0ms
33 http fetch GET 304 https://registry.npmjs.org/@nhost%2freact 1174ms (from cache)
34 silly fetch manifest react@^17.0.2
35 http fetch GET 304 https://registry.npmjs.org/react 67ms (from cache)
36 silly fetch manifest react-dom@^17.0.2
37 http fetch GET 304 https://registry.npmjs.org/react-dom 74ms (from cache)
38 silly placeDep ROOT @nhost/react@0.4.1 REPLACE for: torch@0.1.0 want: 0.4.1
39 timing idealTree Completed in 1976ms
40 timing command:install Completed in 1988ms
41 verbose stack Error: Unsupported URL Type "workspace:": workspace:^
41 verbose stack     at unsupportedURLType (/home/ajones/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:203:15)
41 verbose stack     at fromURL (/home/ajones/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:261:13)
41 verbose stack     at Function.resolve (/home/ajones/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:80:12)
41 verbose stack     at /home/ajones/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:908:36
41 verbose stack     at Array.map (<anonymous>)
41 verbose stack     at Arborist.[buildDepStep] (/home/ajones/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:907:52)
41 verbose stack     at async Arborist.buildIdealTree (/home/ajones/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
41 verbose stack     at async Promise.all (index 1)
41 verbose stack     at async Arborist.reify (/home/ajones/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:136:5)
41 verbose stack     at async Install.install (/home/ajones/.nvm/versions/node/v16.3.0/lib/node_modules/npm/lib/install.js:150:5)
42 verbose cwd /home/ajones/dev/torch
43 verbose Linux 5.10.60.1-microsoft-standard-WSL2
44 verbose argv "/home/ajones/.nvm/versions/node/v16.3.0/bin/node" "/home/ajones/.nvm/versions/node/v16.3.0/bin/npm" "install" "@nhost/react@0.4.1"
45 verbose node v16.3.0
46 verbose npm  v7.15.1
47 error code EUNSUPPORTEDPROTOCOL
48 error Unsupported URL Type "workspace:": workspace:^
49 verbose exit 1```

**Comment by plmercereau** [comment] 2022-04-02 09:36
Hello @ArieJones,
We bumped a patch version to correct the problem.
We are looking for the root cause - a change of behaviour with pnpm/changeset release in our Github action, maybe related to [this issue](https://github.com/pnpm/pnpm/issues/4348).

For the Nhost team:
- Problem not reproduced when publishing locally with the following environment:
  - node v17.8.0
  - npm 8.4.0
  - pnpm 6.32.3
- Dependencies are correct in [@nhost/react@0.4.0](https://cdn.jsdelivr.net/npm/@nhost/react@0.4.0/package.json), not anymore in [@nhost/react@0.4.1](https://cdn.jsdelivr.net/npm/@nhost/react@0.4.1/package.json)
- [Diff between versions](https://github.com/nhost/nhost/compare/%40nhost/react%400.4.0...@nhost/react@0.4.1) don't show any code that may have caused the problem -> we have to identify where the side effect it in our GH action

We'll close this issue once the original problem is found.

**Comment by ArieJones** [comment] 2022-04-02 10:17
Sounds good thanks!

**Closed** 2022-04-03 20:35 UTC
